baseURL = "http://example.com/"
languageCode = "en-us"
title = "Anna Hanna Sarah"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog for COS19 students"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:sarah.chlebowski@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/SarahChleb/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://instagram.com/chlebstrom/"
    name = "instagram"
    weight = 3
